# Generated by Django 4.2.10 on 2024-02-15 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='audio',
        ),
    ]
