# Generated by Django 4.2.10 on 2024-02-15 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='surename',
            new_name='surname',
        ),
    ]
